In [ ]:
#multiclass classification problem in Deep learning  : use dataset iris.csv
#classification means to predict the class
#here there are multiple class which want to predict means more than 2 classes

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

In [ ]:
df=pd.read_csv("/content/drive/MyDrive/deep learning /iris.csv")

In [ ]:
df.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [ ]:
#How many classes in species o/p column which want to predict
df["species"].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [ ]:
df["species"].value_counts()

Iris-setosa        50
Iris-virginica     50
Iris-versicolor    50
Name: species, dtype: int64

In [ ]:
df.shape

(150, 5)

In [ ]:
#here 3 classes which want to predict
#check null values in dataset
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [ ]:
#apply LabelEncoder on o/p column species so call LabelEncoder class
from sklearn.preprocessing import LabelEncoder

#Create the object of LabelEncoder class
le=LabelEncoder()
df["species"]=le.fit_transform(df["species"])
#check
df.head(10)#first 10 records

sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0
5           5.4          3.9           1.7          0.4        0
6           4.6          3.4           1.4          0.3        0
7           5.0          3.4           1.5          0.2        0
8           4.4          2.9           1.4          0.2        0
9           4.9          3.1           1.5          0.1        0

In [ ]:
df["species"].value_counts()

2    50
1    50
0    50
Name: species, dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    int64  
dtypes: float64(4), int64(1)
memory usage: 6.0 KB


In [ ]:
#separate Input features and target means output from dataset
X=df.drop("species",axis=1) #input features
Y=df["species"] #target means output variable

In [ ]:
#train_test_split : to divide data into 70% and 30% from dataset
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,random_state=1,stratify=Y)

In [ ]:
Y_test.value_counts()

2    15
1    15
0    15
Name: species, dtype: int64

In [ ]:
Y_train.value_counts()

2    35
1    35
0    35
Name: species, dtype: int64

In [ ]:
#apply standardscaler on input features(X_train and X_test)
from sklearn.preprocessing import StandardScaler

In [ ]:
#create object of StandardScaler class
ss=StandardScaler()
X_train=ss.fit_transform(X_train)
X_test=ss.transform(X_test)

In [ ]:
X_train

array([[-0.4301064 ,  2.63118533, -1.33269725, -1.30380366],
       [-0.55053619,  0.76918392, -1.16537974, -1.30380366],
       [ 0.65376173,  0.30368356,  0.84243039,  1.44465434],
       [ 1.0150511 ,  0.53643374,  1.0655204 ,  1.18289644],
       [-1.03225536,  0.30368356, -1.44424226, -1.30380366],
       [ 1.0150511 ,  0.07093339,  1.0097479 ,  1.57553329],
       [ 2.09891923, -0.16181679,  1.56747294,  1.18289644],
       [-0.06881702,  2.16568498, -1.44424226, -1.30380366],
       [ 1.61720006, -0.16181679,  1.12129291,  0.52850167],
       [ 0.89462131, -0.39456697,  0.45202286,  0.13586482],
       [-1.03225536, -1.79106803, -0.27301968, -0.25677204],
       [-0.79139578, -0.86006732,  0.06161534,  0.26674377],
       [-1.39354474,  0.30368356, -1.38846976, -1.30380366],
       [ 0.29247235, -0.62731714,  0.50779537,  0.00498586],
       [-0.4301064 , -1.32556767,  0.11738784,  0.13586482],
       [-0.06881702, -0.86006732,  0.73088538,  0.92113853],
       [-1.27311494,  0.

In [ ]:
X_test

array([[ 0.41290214,  0.76918392,  0.89820289,  1.44465434],
       [-0.55053619,  1.9329348 , -1.16537974, -1.04204575],
       [-1.51397453,  0.76918392, -1.33269725, -1.17292471],
       [-1.15268515, -1.32556767,  0.39625036,  0.65938063],
       [ 0.89462131, -0.16181679,  0.34047786,  0.26674377],
       [ 0.29247235, -0.62731714,  0.11738784,  0.13586482],
       [ 1.0150511 , -1.32556767,  1.12129291,  0.79025958],
       [ 0.41290214, -2.02381821,  0.39625036,  0.39762272],
       [ 0.65376173, -0.86006732,  0.84243039,  0.92113853],
       [-0.55053619,  1.9329348 , -1.38846976, -1.04204575],
       [-0.18924682,  3.09668569, -1.27692475, -1.04204575],
       [ 0.29247235, -0.16181679,  0.61934037,  0.79025958],
       [-1.75483411, -0.39456697, -1.33269725, -1.30380366],
       [-1.15268515, -1.55831785, -0.27301968, -0.25677204],
       [-1.51397453,  0.30368356, -1.33269725, -1.30380366],
       [ 1.1354809 , -0.62731714,  0.56356787,  0.26674377],
       [ 1.25591069,  0.

In [ ]:
#Create a neural network 
#create the object of Sequencial model 
model=tf.keras.Sequential([
          tf.keras.layers.Dense(2,activation='relu',input_shape=(X.shape[1],)),
          tf.keras.layers.Dense(3,activation='relu'),
          tf.keras.layers.Dense(3,activation='softmax') #output layer unit of neuron=3              
])

In [ ]:
#compile the model 
#optimizer='adam' if use multiclass in classification algo. and loss='sparse_crossentropy 
model.compile(optimizer="adam", loss="sparse_categorical_crossentropy")

In [ ]:
#train the model , use fit() method
trained_model=model.fit(X_train,Y_train,epochs=30, batch_size=10)

Epoch 1/30
11/11 [==============================] - 0s 1ms/step - loss: 1.1947
Epoch 2/30
11/11 [==============================] - 0s 1ms/step - loss: 1.1891
Epoch 3/30
11/11 [==============================] - 0s 1ms/step - loss: 1.1673
Epoch 4/30
11/11 [==============================] - 0s 2ms/step - loss: 1.1635
Epoch 5/30
11/11 [==============================] - 0s 1ms/step - loss: 1.1494
Epoch 6/30
11/11 [==============================] - 0s 1ms/step - loss: 1.1246
Epoch 7/30
11/11 [==============================] - 0s 1ms/step - loss: 1.1280
Epoch 8/30
11/11 [==============================] - 0s 1ms/step - loss: 1.1262
Epoch 9/30
11/11 [==============================] - 0s 1ms/step - loss: 1.1271
Epoch 10/30
11/11 [==============================] - 0s 1ms/step - loss: 1.0988
Epoch 11/30
11/11 [==============================] - 0s 1ms/step - loss: 1.1040
Epoch 12/30
11/11 [==============================] - 0s 1ms/step - loss: 1.0976
Epoch 13/30
11/11 [==============================

In [ ]:
#testing the model
Y_pred = model.predict(X_test)

In [ ]:
Y_pred

array([[0.20741563, 0.31790996, 0.47467443],
       [0.33793008, 0.31919897, 0.34287098],
       [0.33278129, 0.39412567, 0.27309304],
       [0.2783052 , 0.50849044, 0.21320432],
       [0.2111595 , 0.31819648, 0.47064406],
       [0.3266957 , 0.31308347, 0.36022082],
       [0.20537177, 0.31773838, 0.4768898 ],
       [0.3273786 , 0.40793467, 0.2646867 ],
       [0.2507714 , 0.31923714, 0.42999142],
       [0.33793008, 0.31919897, 0.34287098],
       [0.2558325 , 0.3191332 , 0.4250343 ],
       [0.26667032, 0.3187485 , 0.41458112],
       [0.28978407, 0.48842174, 0.2217942 ],
       [0.27514756, 0.51401377, 0.21083863],
       [0.32150936, 0.42258602, 0.25590464],
       [0.19148314, 0.31627542, 0.49224135],
       [0.17809954, 0.31433713, 0.5075633 ],
       [0.3471775 , 0.35549656, 0.29732594],
       [0.24644358, 0.31928644, 0.43427002],
       [0.21249183, 0.3182899 , 0.46921825],
       [0.13008511, 0.30203834, 0.5678766 ],
       [0.31906477, 0.42859024, 0.25234506],
       [0.

In [ ]:
Y_pred = Y_pred.argmax(axis=1) #select highest probability of multiple class column wise
#and hold in Y_pred
#argmax : inbuilt method ,select highest prob. of multiple class
Y_pred

array([2, 2, 1, 1, 2, 2, 2, 1, 2, 2, 2, 2, 1, 1, 1, 2, 2, 1, 2, 2, 2, 1,
       2, 1, 1, 2, 1, 2, 0, 1, 1, 0, 1, 1, 2, 2, 1, 1, 1, 2, 2, 2, 2, 0,
       1])

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(Y_test,Y_pred))

              precision    recall  f1-score   support

           0       1.00      0.20      0.33        15
           1       0.37      0.47      0.41        15
           2       0.52      0.80      0.63        15

    accuracy                           0.49        45
   macro avg       0.63      0.49      0.46        45
weighted avg       0.63      0.49      0.46        45



In [ ]:
#f1-score=2*R*P/(P+R) it is harmonic mean of recall and precision